# Generated by Django 3.0.5 on 2020-05-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(path='/static/')),
            ],
        ),
    ]
