# Generated by Django 3.0.5 on 2020-05-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_staticgraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticgraph',
            name='image',
            field=models.FilePathField(path='/static'),
        ),
    ]
