# Generated by Django 3.0.5 on 2020-05-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20200510_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticgraph',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
