# Generated by Django 3.0.5 on 2020-05-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_auto_20200510_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticGraph',
        ),
    ]
