# Generated by Django 3.0.5 on 2020-05-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_delete_staticgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/', verbose_name='image')),
            ],
        ),
    ]
