# Generated by Django 3.0.5 on 2020-05-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_staticgraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='min_percent_questions',
        ),
    ]
