# Generated by Django 3.0.5 on 2020-05-09 00:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200509_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(default='user', max_length=100)
        ),
    ]
