# Generated by Django 3.0.5 on 2020-05-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.Admin'),
            preserve_default=False,
        ),
    ]
