# Generated by Django 3.0.5 on 2020-05-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_user_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(default='empty', max_length=256),
            preserve_default=False,
        ),
    ]
