# Generated by Django 3.0.5 on 2020-05-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
