# Generated by Django 3.0.5 on 2020-05-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20200509_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='title_company',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='admin@mail.com', max_length=35),
            preserve_default=False,
        ),
    ]
